// <auto-generated />
namespace KinectMotionAnalyzer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addjointstatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addjointstatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201304190419068_add joint status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
