// <auto-generated />
namespace KinectMotionAnalyzer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedjointweightstoaction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedjointweightstoaction));
        
        string IMigrationMetadata.Id
        {
            get { return "201305180444326_added joint weights to action"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
