// <auto-generated />
namespace KinectMotionAnalyzer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class newdata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newdata));
        
        string IMigrationMetadata.Id
        {
            get { return "201304141650404_new data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
