// <auto-generated />
namespace KinectMotionAnalyzer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removedepthdata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedepthdata));
        
        string IMigrationMetadata.Id
        {
            get { return "201304170515442_remove depth data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
