// <auto-generated />
namespace KinectMotionAnalyzer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removevirtual : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removevirtual));
        
        string IMigrationMetadata.Id
        {
            get { return "201304171923208_remove virtual"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
