// <auto-generated />
namespace KinectMotionAnalyzer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class simpletest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(simpletest));
        
        string IMigrationMetadata.Id
        {
            get { return "201304180219283_simple test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
